[package]
name = "height-mapper"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = {version = "0.34.1", features = ["convert-bytemuck"] }
realsense-rust = "1.2.3"
simple-icp = {git ="https://github.com/utahrobotics/simple-icp.git"}
rerun = { version = "0.25.1", features = ["sdk"], default-features = false }
rayon = "1.11.0"
pasture-algorithms = "0.5.0"
pasture-core = "0.5.0"
pasture-derive = "0.5.0"
bytemuck = "1.24.0"
typenum = "1.13.0"
kd-tree = "0.3.0"
image = "0.25.8"
